### ISSUE TITLE
S3_Multipart_Upload failure

### ISSUE THREAD

**Issue by kkranen** [samoconnor/AWSS3.jl#11]
Hello samoconnor and company,
I'm attempting to use your package for large file upload but I'm having an error upon method call (see below). I'm currently using Julia 0.6.0.
Thanks, and I hope you guys can solve this issue!

<img width="1028" alt="screen shot 2017-07-10 at 10 36 00 am" src="https://user-images.githubusercontent.com/8432535/28031279-9ba34c5c-655b-11e7-9d6b-2ecf1ea8a11a.png">

**Comment by samoconnor** [comment]
Hi @kkranen,

Thanks for reporting this, I've committed changes to both AWS3.jl and AWSCore.jl to try to fix this.

https://github.com/samoconnor/AWSS3.jl/commit/6423211a132720e65326103c8ea7da2242bf491b https://github.com/samoconnor/AWSS3.jl/commit/a9e5f192ad1326ed9c72aa682907c735a1a561ce https://github.com/samoconnor/AWSS3.jl/commit/afa045a18f50766bb81ccd10e133c8a3f6051526 

https://github.com/samoconnor/AWSCore.jl/commit/6905cf58363fde1bcc20734dc1bad9834be06613

Also note that `chunk_size` 44000 is probably not what you want. I've renamed it to `chunk_size_mb` for clarity.


@barcharcraz
