### ISSUE TITLE
s3_exists should use HEAD instead of GETting a small range

### ISSUE THREAD

**Issue by s2maki** [samoconnor/AWSS3.jl#12]
GET on a URL causes Requests.jl to parse the resulting data by its content type.  Using GET with a byte range of 0-0 will return a single byte (the first byte in the file), causing such parsing to fail.

Better to use HEAD instead of GET when testing for object existence.

**Comment by samoconnor** [comment]
Thanks @s2maki 

I'm now calling `s3_get_meta` : https://github.com/samoconnor/AWSS3.jl/commit/79b1b47928504a531bcf320fc257d2ae8f5ce706#diff-bfa26c7ba85a0e383f74a605295a9456R210

**Comment by s2maki** [comment]
Thanks!
