### ISSUE TITLE
[question] the process behind raw=true

### ISSUE THREAD

**Issue by jingpengw** [samoconnor/AWSS3.jl#18]
if I set the raw=true in s3_get, will the file decompressed in the S3 server side or client side?

also, when I set the "Content-Encoding" in s3_put, will the data be automatically compressed in the client side, or do I need to compress it before ?

**Comment by jingpengw** [comment]
I just ran some tests, it seems that raw option does not do anything...

**Comment by samoconnor** [comment]
Hi @jingpengw,

The package does not do any compression or decompression.

Whatever you pass to the `data` parameter of `s3_put` is sent verbatim to S3 as the body of the PUT request.

The value you pass to the `encoding=` parameter is sent as the `Content-Encoding` header.

The [S3 PUT doc](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUT.html) says: _"Content-Encoding: Specifies what content encodings have been applied to the object and thus what decoding mechanisms must be applied to obtain the media-type referenced by the Content-Type header field."_

My understanding is that the S3 server does not interpret this header, or do any compression or decompression. I think it simply returns to GET requests the data and the `Content-Encoding` header exactly as provided in PUT requests. i.e. If you pre-compress some data and set `Content-Encoding` when you upload it, then a browser that downloads the data will probably automatically de-compress it.

As far as I know, HTTP.jl does not automatic decompression based on the `Content-Encoding` header. @quinnj ?

The `raw=true` option in `s3_get` disables parsing of the result for xml, json, and string mime types:
https://github.com/JuliaCloud/AWSCore.jl/blob/master/src/AWSCore.jl#L457

For binary data `raw=true` has no effect. In the future the special handling of xml, json, and string mime types might be extended to include other types (media files?, serialised Julia objects?) and/or to be `Content-Encoding` aware. In that case `raw=true` would disable that behaviour.

**Comment by jingpengw** [comment]
thanks for the detailed explanation. so I don't need to worry about this since I work with binary files most of the time.
