### ISSUE TITLE
support for reading compressed files (in gz)

### ISSUE THREAD

**Issue by somasdhavala** [samoconnor/AWSS3.jl#2]
@samoconnor Not sure if it is the right place to ask, but is there support available for reading compressed files on s3. 
If it is not there, say, do I consider the response to the call 
`s3_get(aws,"bucket","key")`
as a binary stream and process it as such?

**Comment by somasdhavala** [comment]
@samoconnor sorry, just figured that, 
`s3_get_file(aws,"bucket","file_on_s3","local_file_name-_to_write_to")`
would seem to solve it. if there is any better way, please do let me know
thanks

**Comment by samoconnor** [comment]
Hi @somasdhavala 

`s3_get` [returns `data(::Response)`](https://github.com/samoconnor/AWSS3.jl/blob/master/src/AWSS3.jl#L100) which returns [either a string or an array of `UInt8` depending on the Content-Type](https://github.com/samoconnor/AWSCore.jl/blob/master/src/http.jl#L144).
So, `s3_get` should return compressed data as `Vector{UInt8}` which can then be passed to an appropriate decompression function.

If you need a stream, you can call the S3 `GET` API directly like this:
```julia
    stream = s3(aws, "GET", "bucket"; path = "myfile.gz",
                                    return_stream = true)
```
