### ISSUE TITLE
anyway to set content-encoding while uploading an array?

### ISSUE THREAD

**Issue by jingpengw** [samoconnor/AWSS3.jl#5]
Hi, @samoconnor , I am trying to use your package. it is pretty handy. the download and upload works great. I still need to setup the `content-encoding` as gzip of the files. It seems that it is not supported?
I find an option to setup content-type though.

**Comment by samoconnor** [comment]
Hi @jingpengw, thanks for suggesting this, see f968ca8dbe47424b7d4d1b03f5be87a0bb188ac8 for new `encoding=` option on `s3_put`.
